set(OPTFLAGS "${OPTFLAGS} -O3 -Tmppadcos_ddr.ld -Wl,--defsym=USER_STACK_SIZE=128000")

set(CMAKE_C_FLAGS_RELEASE "${OPTFLAGS}" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELEASE "${OPTFLAGS}" CACHE STRING "")
set(CMAKE_BUILD_TYPE "Release" CACHE STRING "")
